export const FILE_EXPLORER_ERROR_CODES = {
  CWD_INVALID: 'CWD_INVALID',
  PATH_INVALID: 'PATH_INVALID',
  NOT_A_DIRECTORY: 'NOT_A_DIRECTORY',
  NOT_A_FILE: 'NOT_A_FILE',
  FILE_TOO_LARGE: 'FILE_TOO_LARGE',
  EMPTY_PATH: 'EMPTY_PATH',
  FILE_EXISTS: 'FILE_EXISTS',
  DIR_EXISTS: 'DIR_EXISTS',
  NOT_FOUND: 'NOT_FOUND',
  DEST_EXISTS: 'DEST_EXISTS',
  DELETE_FAILED: 'DELETE_FAILED',
  COPY_FAILED: 'COPY_FAILED',
  PASTE_FAILED: 'PASTE_FAILED',
  RENAME_FAILED: 'RENAME_FAILED',
  SAVE_FAILED: 'SAVE_FAILED',
  LOAD_FAILED: 'LOAD_FAILED',
  BINARY_FILE: 'BINARY_FILE',
  INVALID_CONTENT: 'INVALID_CONTENT',
  NOTHING_TO_COPY: 'NOTHING_TO_COPY',
  NOTHING_TO_PASTE: 'NOTHING_TO_PASTE',
  PASTE_INTO_SELF: 'PASTE_INTO_SELF',
  DROP_INTO_SELF: 'DROP_INTO_SELF',
} as const

export type FileExplorerErrorCode =
  (typeof FILE_EXPLORER_ERROR_CODES)[keyof typeof FILE_EXPLORER_ERROR_CODES]
